Int att1;
Str att2;
Str att3;
Int att4;
Str att5;
Float att6;
Str att7;
Int att8;
Int att9;
Int att10;
Int att11;
Int att12;
Float att13;
Float att14;
Float att15;
Str att16;
Str att17;
Str att18;
Str att19;
Str att20;
Str att21;
Str att22;
Str att23;
Int att24;
Int att25;
Str att26;
Float att27;
Str att28;
Str att29;
Str att30;
Int att31;
Str att32;
Int att33;
Int att34;
Int att35;
Int att36;
Int att37;
Float att38;
Float att39;
Float att40;
Str att41;
Str att42;
Str att43;
Str att44;
Str att45;
Str att46;
Str att47;
Str att48;

att1 = left.s_suppkey;
att2 = left.s_name;
att3 = left.p_address;
att4 = left.s_nationkey;
att5 = left.s_phone;
att6 = left.s_acctbal;
att7 = left.s_commnet;
att8 = left.l_orderkey;
att9 = left.l_partkey;
att10 = left.l_suppkey;
att11 = left.l_linenumber;
att12 = left.l_quantity;
att13 = left.l_extendedprice;
att14 = left.l_discount;
att15 = left.l_tax;
att16 = left.l_returnflag;
att17 = left.l_linestatus;
att18 = left.l_shipdate;
att19 = left.l_commitdate;
att20 = left.l_receiptdate;
att21 = left.l_shipinstruct;
att22 = left.l_shipmode;
att23 = left.l_comment;
att24 = left.o_orderkey;
att25 = left.o_custkey;
att26 = left.o_orderstatus;
att27 = left.o_totalprice;
att28 = left.o_orderdate;
att29 = left.o_orderpriority;
att30 = left.o_clerk;
att31 = left.o_shippriority;
att32 = left.o_comment;
att33 = right.l_orderkey;
att34 = right.l_partkey;
att35 = right.l_suppkey;
att36 = right.l_linenumber;
att37 = right.l_quantity;
att38 = right.l_extendedprice;
att39 = right.l_discount;
att40 = right.l_tax;
att41 = right.l_returnflag;
att42 = right.l_linestatus;
att43 = right.l_shipdate;
att44 = right.l_commitdate;
att45 = right.l_receiptdate;
att46 = right.l_shipinstruct;
att47 = right.l_shipmode;
att48 = right.l_comment;

att1.WriteOut (toMe);
att2.WriteOut (toMe);
att3.WriteOut (toMe);
att4.WriteOut (toMe);
att5.WriteOut (toMe);
att6.WriteOut (toMe);
att7.WriteOut (toMe);
att8.WriteOut (toMe);
att9.WriteOut (toMe);
att10.WriteOut (toMe);
att11.WriteOut (toMe);
att12.WriteOut (toMe);
att13.WriteOut (toMe);
att14.WriteOut (toMe);
att15.WriteOut (toMe);
att16.WriteOut (toMe);
att17.WriteOut (toMe);
att18.WriteOut (toMe);
att19.WriteOut (toMe);
att20.WriteOut (toMe);
att21.WriteOut (toMe);
att22.WriteOut (toMe);
att23.WriteOut (toMe);
att24.WriteOut (toMe);
att25.WriteOut (toMe);
att26.WriteOut (toMe);
att27.WriteOut (toMe);
att28.WriteOut (toMe);
att29.WriteOut (toMe);
att30.WriteOut (toMe);
att31.WriteOut (toMe);
att32.WriteOut (toMe);
att33.WriteOut (toMe);
att34.WriteOut (toMe);
att35.WriteOut (toMe);
att36.WriteOut (toMe);
att37.WriteOut (toMe);
att38.WriteOut (toMe);
att39.WriteOut (toMe);
att40.WriteOut (toMe);
att41.WriteOut (toMe);
att42.WriteOut (toMe);
att43.WriteOut (toMe);
att44.WriteOut (toMe);
att45.WriteOut (toMe);
att46.WriteOut (toMe);
att47.WriteOut (toMe);
att48.WriteOut (toMe);
